### PR TITLE
Various fix

### PR DESCRIPTION
**Pull request by julienba**
Hello Felipe,                                                                                                                                                                                               

I improved build.xml and home.textile. Presently home.textile throws an exception in playframework website, try http://localhost:9000/@documentation/modules/elasticsearch/home for reproduce local error.

I also fixed one bug in ReflectionUtil.java. When I try to use ElasticSearch.search method, I've an exception due to Integer parsing. My solution is not very elegant fix, I think they are a better way for do that.

I created one sample project if you would quickly reproduce this errors: https://github.com/julienba/ElasticSearchDemo

Julien

### CODE REVIEW

**Comment by julienba** [comment]
Any updates ?

**Comment by feliperazeek** [comment]
Oh man I thought this was merged, so sorry! Looks like there's a conflict let me look into it.

**Comment by bgooren** [comment]
Some of these fixes are also included in my commits, which is probably why you are getting conflicts

**Comment by feliperazeek** [comment]
ElasticSearch.builder has a problem though since it's using a new version of ES.

**Comment by bgooren** [comment]
What kind of problem?

**Pull request merged**
